EXP_NAME: 'rich_hrnet_testing'
PROJECT_NAME: 'DECO_RICH_Testing'
OUTPUT_DIR: 'deco_results'
CONDOR_DIR: '/is/cluster/fast/achatterjee/Tuning/rich'
DATASET:
  BATCH_SIZE: 16
  NUM_WORKERS: 4
  NORMALIZE_IMAGES: [True]
OPTIMIZER:
  TYPE: 'adam'
  LR: [5e-5]
  NUM_UPDATE_LR: 3
TRAINING:
  ENCODER: 'hrnet'
  CONTEXT: [True]
  NUM_EPOCHS: 1
  NUM_EARLY_STOP: 10
  SUMMARY_STEPS: 5
  CHECKPOINT_EPOCHS: 5
  DATASETS: ['rich']
  DATASET_MIX_PDF: ['1.']
  DATASET_ROOT_PATH: '/is/cluster/fast/achatterjee/Datasets/rich/npzs'
  BEST_MODEL_PATH: '/is/cluster/fast/achatterjee/weights/prox_rich/prox_rich_cropped_hrnet_tuning_dataset.normalizeimages-True_optimizer.lr-5e-05_training.lossweights-10.0_best.pth'
  LOSS_WEIGHTS: [1.]
  PAL_LOSS_WEIGHTS: 0.0
VALIDATION:
  SUMMARY_STEPS: 1000
  DATASETS: ['rich']
  MAIN_DATASET: 'rich'